
package vt.qlkdtt.yte.passport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "passportWS", targetNamespace = "http://passport.viettel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PassportWS {

    /**
     * 
     * @param userName
     * @param ipCheck
     * @param domainCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateIncludeIp", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.ValidateIncludeIp")
    @ResponseWrapper(localName = "validateIncludeIpResponse", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.ValidateIncludeIpResponse")
    @Action(input = "http://passport.viettel.com/passportWS/validateIncludeIpRequest", output = "http://passport.viettel.com/passportWS/validateIncludeIpResponse")
    public String validateIncludeIp(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "domainCode", targetNamespace = "")
                    String domainCode,
            @WebParam(name = "ipCheck", targetNamespace = "")
                    String ipCheck);

    /**
     * 
     * @param domainCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRolesOfApp", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetRolesOfApp")
    @ResponseWrapper(localName = "getRolesOfAppResponse", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetRolesOfAppResponse")
    @Action(input = "http://passport.viettel.com/passportWS/getRolesOfAppRequest", output = "http://passport.viettel.com/passportWS/getRolesOfAppResponse")
    public String getRolesOfApp(
            @WebParam(name = "domainCode", targetNamespace = "")
                    String domainCode);

    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllowedApp", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetAllowedApp")
    @ResponseWrapper(localName = "getAllowedAppResponse", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetAllowedAppResponse")
    @Action(input = "http://passport.viettel.com/passportWS/getAllowedAppRequest", output = "http://passport.viettel.com/passportWS/getAllowedAppResponse")
    public String getAllowedApp(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName);

    /**
     * 
     * @param domainCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppFunctions", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetAppFunctions")
    @ResponseWrapper(localName = "getAppFunctionsResponse", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.GetAppFunctionsResponse")
    @Action(input = "http://passport.viettel.com/passportWS/getAppFunctionsRequest", output = "http://passport.viettel.com/passportWS/getAppFunctionsResponse")
    public String getAppFunctions(
            @WebParam(name = "domainCode", targetNamespace = "")
                    String domainCode);

    /**
     * 
     * @param userName
     * @param domainCode
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://passport.viettel.com/", className = "com.viettel.passport.ValidateResponse")
    @Action(input = "http://passport.viettel.com/passportWS/validateRequest", output = "http://passport.viettel.com/passportWS/validateResponse")
    public String validate(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "domainCode", targetNamespace = "")
                    String domainCode);

}
